allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - geosite:private
  - geosite:cn
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  fallback:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://[2001:4860:4860::64]
  - tls://[2001:4860:4860::8888]
  - tls://[2001:4860:4860::8844]
  - tls://8.8.4.4
  - tls://[2606:4700:4700::1111]
  - tls://[2606:4700:4700::1001]
  - https://[2620:fe::9]/dns-query
  - tls://[2620:fe::9]
  - tls://[2620:fe::fe]
  - tls://[2620:fe::fe:9]
  - tls://149.112.112.9
  - tls://149.112.112.112
  - tls://9.9.9.9
  - tls://94.140.14.141
  - https://[2a10:50c0::2:ff]
  - tls://[2a10:50c0::2:ff]
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
geox-url:
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-Country.mmdb
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
ntp:
  enable: true
  interval: 30
  port: 123
  server: time.apple.com
  write-to-system: false
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 64
  cipher: auto
  name: ğŸ‡¯ğŸ‡µ1 |  1.8MB/s|54%|Youtube|Ope...
  network: ws
  port: 1443
  server: sslvpn.51job.com
  skip-cert-verify: true
  tfo: false
  tls: true
  type: vmess
  udp: true
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  ws-opts:
    headers:
      Host: centos7
    path: /634c5c4f9782
- name: ğŸ‡¯ğŸ‡µæ—¥æœ¬
  password: 2a9b85bd-27cc-4e3b-b77d-54dbe5bc23af
  port: 443
  server: aws-linkhy17.liangxin1.xyz
  skip-cert-verify: true
  sni: www.apple.com.cn
  tls: false
  type: hysteria2
- cipher: rc4-md5
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬|@ripaojiedian
  password: efanccyun
  plugin: obfs
  plugin-opts:
    host: 202507121073737-BbgY2abS77.download.microsoft.com
    mode: http
  port: 8766
  server: cn01.efan8867801.xyz
  tfo: false
  type: ss
- cipher: aes-256-gcm
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬2|@ripaojiedian
  password: 823e135ed103
  plugin: v2ray-plugin
  plugin-opts:
    host: jp7v1.lingjfjkm002.com
    mode: websocket
    mux: true
    path: /dchlbvrbbotc
    skip-cert-verify: false
    tls: true
  port: 636
  server: 137.220.191.40
  tfo: false
  type: ss
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: d0d08cddacc3190ea81b1b792e1b5fde
  port: 41225
  server: 36.151.192.26
  skip-cert-verify: true
  sni: www.baidu.com
  type: trojan
- name: æ—¥æœ¬4|@ripaojiedian
  network: tcp
  password: d0d08cddacc3190ea81b1b792e1b5fde
  port: 4445
  server: 36.151.192.26
  skip-cert-verify: true
  sni: www.baidu.com
  type: trojan
- alterId: 0
  cipher: auto
  name: æ—¥æœ¬v2|@ripaojiedian
  network: kcp
  port: '2389'
  server: 8.211.145.146
  servername: ''
  tls: false
  type: vmess
  uuid: 9f9f395b-e9b2-4cfd-85b3-0425f0e11ad7
- name: ğŸ‡¯ğŸ‡µ_æ—¥æœ¬_1
  network: tcp
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2096
  server: 156.238.19.69
  skip-cert-verify: true
  sni: vle.amclubdns.dpdns.org
  type: trojan
  udp: true
- name: ğŸ‡¯ğŸ‡µ_æ—¥æœ¬_2
  network: tcp
  port: 34045
  server: 160.250.65.124
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  skip-cert-verify: true
  tls: false
  type: vless
  udp: true
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
- name: ğŸ‡¯ğŸ‡µ_æ—¥æœ¬_3
  network: tcp
  port: 34045
  server: 160.250.65.148
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  skip-cert-verify: true
  tls: false
  type: vless
  udp: true
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
- name: ğŸ‡¯ğŸ‡µ_æ—¥æœ¬_4
  network: ws
  port: 8880
  server: 103.116.7.186
  servername: Telegram-channel-WangCai2
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      host: Telegram-channel-WangCai2
    path: /telegramğŸ‡¨ğŸ‡³ @wangcai2 /?ed=2560
- name: ğŸ‡¯ğŸ‡µ_æ—¥æœ¬_5
  network: ws
  port: 8880
  server: 103.245.228.186
  servername: Telegram-channel-WangCai2
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      host: Telegram-channel-WangCai2
    path: /telegramğŸ‡¨ğŸ‡³ @wangcai2 /?ed=2560
- name: ğŸ‡¯ğŸ‡µ_æ—¥æœ¬_6
  network: ws
  port: 8880
  server: 103.245.229.186
  servername: Telegram-channel-WangCai2
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      host: Telegram-channel-WangCai2
    path: /telegramğŸ‡¨ğŸ‡³ @wangcai2 /?ed=2560
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 06
  network: ws
  port: 443
  server: 13.230.34.30
  servername: steep.skyfigure.top
  tls: true
  type: vless
  udp: true
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  ws-opts:
    headers:
      Host: steep.skyfigure.top
    path: TelegramğŸ‡¨ğŸ‡³ @pgkj666 /?ed=2560
- cipher: aes-256-gcm
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01
  password: 70a0b8103356
  plugin: v2ray-plugin
  plugin-opts:
    host: jp5v1.lingjfjkm002.com
    mode: websocket
    mux: true
    path: /bezradrqccl
    tls: true
  port: 636
  server: 137.220.142.139
  type: ss
  udp: true
- auth: b74c908a-3031-420c-a79c-7b0a37d8c452
  down: 20
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 11
  password: b74c908a-3031-420c-a79c-7b0a37d8c452
  port: 60007
  server: gy3.mlshu.top
  skip-cert-verify: true
  type: hysteria2
  udp: true
  up: 20
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 13
  network: ws
  port: 443
  server: 217.142.236.93
  servername: steep.skyfigure.top
  tls: true
  type: vless
  udp: true
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  ws-opts:
    headers:
      Host: steep.skyfigure.top
    path: TelegramğŸ‡¨ğŸ‡³ @pgkj666 /?ed=2560
- client-fingerprint: chrome
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 14
  network: ws
  port: 12338
  server: 211.57.29.229
  servername: edmx.ambercc.filegear-sg.me
  tls: true
  type: vless
  udp: true
  uuid: ee6774c0-9b19-4ff1-8b30-2da4b71977e2
  ws-opts:
    headers:
      Host: edmx.ambercc.filegear-sg.me
    path: /?ed=2560&proxyip=ts.hpc.tw
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 08
  password: 038d43d6-30de-4b45-8660-4c0ccfbdc85c
  port: 23514
  server: c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8.1kmei.com
  skip-cert-verify: true
  sni: cn.bing.com
  type: trojan
  udp: true
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µJP-149.22.87.204-0276 | 35.609MB
  password: shadowsocks
  port: 443
  server: 149.22.87.204
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡¯ğŸ‡µJP-149.22.87.241-0275 | 35.467MB
  password: shadowsocks
  port: 443
  server: 149.22.87.241
  type: ss
- client-fingerprint: chrome
  name: æ—¥æœ¬ 006
  network: ws
  port: 2095
  server: 156.238.18.163
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  ws-opts:
    headers:
      Host: redw.pooriam.ir
    path: /TM-AZARBAYJAB1TM-AZARBAYJAB1TM-AZARBAYJAB1
- client-fingerprint: chrome
  name: æ—¥æœ¬ 007
  network: ws
  port: 2052
  server: 156.238.18.165
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  ws-opts:
    headers:
      Host: redw.pooriam.ir
    path: /TM-AZARBAYJAB1TM-AZARBAYJAB1TM-AZARBAYJAB1
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 24
  network: ws
  password: 2ba7e4d0-f2f9-456e-a43e-f5a724d7e367
  port: 20230
  server: jp005.421421.xyz
  skip-cert-verify: true
  sni: www.alibaba.com
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: www.alibaba.com
    path: ''
- auth: JoJs97fUt6WEtqNj56ycj2EqfHY
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 22
  password: JoJs97fUt6WEtqNj56ycj2EqfHY
  port: 22829
  server: 18.183.32.165
  skip-cert-verify: true
  sni: bing.com
  type: hysteria2
  udp: true
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 26
  network: ws
  password: f08d6a6b-a0b3-410e-a0ba-eae71b521904
  port: 20230
  server: jp007.421421.xyz
  skip-cert-verify: true
  sni: www.alibaba.com
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: www.alibaba.com
    path: ''
- alterId: 2
  cipher: auto
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02
  network: ws
  port: 30806
  server: v6.heduian.link
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  ws-opts:
    headers:
      Host: ocbc.com
    path: /oooo
- auth: Y9vRstWcTHECGcKnayA2VYiUXs
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 23
  password: Y9vRstWcTHECGcKnayA2VYiUXs
  port: 35562
  server: 13.112.101.203
  skip-cert-verify: true
  sni: bing.com
  type: hysteria2
  udp: true
- auth: jyEWQRbJATgWMu3XQtRvxb2h0
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 21
  password: jyEWQRbJATgWMu3XQtRvxb2h0
  port: 25635
  server: 47.79.34.232
  skip-cert-verify: true
  sni: bing.com
  type: hysteria2
  udp: true
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 09
  network: ws
  port: 30060
  server: 183.96.245.165
  servername: steep.skyfigure.top
  tls: true
  type: vless
  udp: true
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  ws-opts:
    headers:
      Host: steep.skyfigure.top
    path: TelegramğŸ‡¨ğŸ‡³ @pgkj666 /?ed=2560
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 17
  network: ws
  port: 443
  server: 141.147.185.15
  servername: steep.skyfigure.top
  tls: true
  type: vless
  udp: true
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  ws-opts:
    headers:
      Host: steep.skyfigure.top
    path: TelegramğŸ‡¨ğŸ‡³ @pgkj666 /?ed=2560
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 19
  network: ws
  port: 22735
  server: 140.83.57.183
  servername: steep.skyfigure.top
  tls: true
  type: vless
  udp: true
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  ws-opts:
    headers:
      Host: steep.skyfigure.top
    path: TelegramğŸ‡¨ğŸ‡³ @pgkj666 /?ed=2560
proxy-groups:
- name: âœˆï¸ é€‰æ‹©ä»£ç†
  proxies:
  - âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  - âš–ï¸ è´Ÿè½½å‡è¡¡
  - ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  - DIRECT
  type: select
- expected-status: 204
  include-all-proxies: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  timeout: 3000
  tolerance: 10
  type: url-test
  url: https://www.gstatic.com/generate_204
- expected-status: 204
  include-all-proxies: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡
  strategy: consistent-hashing
  timeout: 3000
  type: load-balance
  url: https://www.gstatic.com/generate_204
- expected-status: 204
  include-all-proxies: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  timeout: 3000
  type: select
  url: https://www.gstatic.com/generate_204
rule-providers:
  applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
rules:
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN-SUFFIX,ghproxy.com,DIRECT
- DOMAIN-SUFFIX,gofile.io,DIRECT
- RULE-SET,applications,DIRECT
- GEOSITE,category-ads-all,REJECT
- GEOSITE,bing,âœˆï¸ é€‰æ‹©ä»£ç†
- GEOSITE,microsoft,âœˆï¸ é€‰æ‹©ä»£ç†
- GEOSITE,private,DIRECT
- GEOIP,private,DIRECT
- GEOSITE,geolocation-cn,DIRECT
- GEOIP,cn,DIRECT
- GEOSITE,geolocation-!cn,âœˆï¸ é€‰æ‹©ä»£ç†
- MATCH,âœˆï¸ é€‰æ‹©ä»£ç†
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
