allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - 94.140.14.141
  - udp://[2a10:50c0::1:ff]
  - udp://[2a10:50c0::2:ff]
  - 149.112.112.9
  - 149.112.112.112
  - udp://[2620:fe::fe]
  - udp://[2620:fe::9]
  direct-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - RULE-SET,other_ssk_lan_non_ip
  - RULE-SET,geosite_private_domains
  - RULE-SET,geosite_connectivity_check
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://1dot1dot1dot1.cloudflare-dns.com
  - tls://unfiltered.adguard-dns.com
  - tls://dns.mullvad.net
  - https://dns.nextdns.io/dns-query
  proxy-server-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
ntp:
  enable: true
  interval: 30
  port: 123
  server: time.apple.com
  write-to-system: false
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- name: ç¾å›½ 079
  port: 443
  server: 135.148.74.155
  servername: 147135004002.sec20org.com
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: 54694a33-a8dc-47dd-bc38-acd3971e0055
- alterId: 0
  cipher: auto
  name: ç¾å›½ 062
  network: ws
  port: 443
  server: JJJjjjjjmMMmM.4444926.XYZ
  tls: true
  type: vmess
  uuid: dc50eb1d-244d-4711-b168-a101a5e6fb1b
  ws-opts:
    headers:
      Host: jjjjjjjjmmmmm.4444926.xyz
    path: /awmqq79B17rfnpXiNaWb
- name: 'Channel id: @ShadowProxy66ğŸ‡ºğŸ‡¸'
  password: 65a43b6e-19c5-4fab-b960-d110a07d66a4
  port: 3234
  server: 209.141.47.127
  skip-cert-verify: true
  tls: false
  type: hysteria2
- alterId: 0
  cipher: auto
  name: ç¾å›½ 061
  network: ws
  port: 443
  server: sSsdCVfBGNjkI.931.PP.Ua
  tls: true
  type: vmess
  uuid: a4e8ec0a-75d0-4fc5-837a-4973ed3a9d3e
  ws-opts:
    headers:
      Host: sSsdCVfBGNjkI.931.PP.Ua
    path: /14Fziqw1hYgCXNutkS5H
- alterId: 0
  cipher: auto
  name: ç¾å›½ 057
  network: ws
  port: 443
  server: FffvvVbnhJui8.222560.XYz
  tls: true
  type: vmess
  uuid: 7701ddf5-6a48-401b-a3ec-8af52b6deb48
  ws-opts:
    headers:
      Host: FffvvVbnhJui8.222560.XYz
    path: /mlyR5tmcKx3hweBopuhWEbIX
- cipher: aes-256-cfb
  name: ğŸ‡¬ğŸ‡§_GB_è‹±å›½->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  password: f8f7aCzcPKbsF8p3
  port: 989
  server: 51.15.17.169
  type: ss
- alterId: 0
  cipher: auto
  name: ç¾å›½ 013
  network: ws
  port: 8443
  server: us01.sh-cloudflare.sbs
  servername: us01.sh-cloudflare.sbs
  tls: true
  type: vmess
  udp: true
  uuid: 2bd0c9d7-f239-437e-a1e1-6cf830af2a1a
  ws-opts:
    headers:
      Host: us01.sh-cloudflare.sbs
    path: /
- alterId: 0
  cipher: auto
  name: ç¾å›½ 059
  network: ws
  port: 443
  server: sssssssxxxx.2032.pp.ua
  tls: true
  type: vmess
  uuid: 4174b95d-115e-4d39-add6-1f8db95bb860
  ws-opts:
    headers:
      Host: sssssssxxxx.2032.pp.ua
    path: /6We3U9Df1WGxgFnoFPw1
- auth: 5CBqBh6MeDq6GajcilBiDg==
  name: 'Channel id: @ShadowProxy66ğŸ‡ºğŸ‡¸ #2'
  password: 5CBqBh6MeDq6GajcilBiDg==
  port: 61001
  server: 192.227.152.86
  skip-cert-verify: true
  sni: 192-227-152-86.nip.io
  tls: false
  type: hysteria2
- name: ç¾å›½ 037
  network: ws
  password: 6757b7d6-fa32-4708-b5d1-30e3cf928b51
  port: 443
  server: 104.21.6.179
  sni: ZZzzzZZ.890601.XYZ
  type: trojan
  ws-opts:
    headers:
      Host: ZZzzzZZ.890601.XYZ
    path: /l96MZ8se5Kl2p8BiMhP42l
- name: ç¾å›½ 060
  network: ws
  password: ttfang
  port: 443
  server: 20.235.105.146
  sni: ttfang.fange.me
  type: trojan
  ws-opts:
    headers:
      Host: ttfang.fange.me
    path: /
- alterId: 0
  cipher: auto
  country: ğŸZZ
  delay: 1890
  h2-opts: {}
  http-opts: {}
  name: ç¾å›½ - æ°´ç‰›åŸ - HostPapa - 17
  network: ws
  port: 8080
  server: s1.cn-db.top
  servername: 100-68-98-225.s1.cn-db.top
  skip-cert-verify: true
  type: vmess
  uuid: 248be52b-35d9-34cb-9b73-e12b78bc1301
  ws-opts:
    headers:
      HOST: 100-68-98-225.s1.cn-db.top
    path: /dabai.in172.67.86.139
- alterId: 0
  cipher: auto
  country: ğŸZZ
  delay: 1996
  h2-opts: {}
  http-opts: {}
  name: ç¾å›½ - æ°´ç‰›åŸ - HostPapa - 18
  network: ws
  port: 80
  server: s4.cn-db.top
  servername: 100-242-127-44.s4.cn-db.top
  skip-cert-verify: true
  type: vmess
  uuid: 248be52b-35d9-34cb-9b73-e12b78bc1301
  ws-opts:
    headers:
      HOST: 100-242-127-44.s4.cn-db.top
    path: /dabai.in172.64.1.52
- delay: 2361
  name: ç¾å›½ - è–è·è¥¿ - Cloudflare, Inc. - 19
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2053
  server: 103.160.204.26
  skip-cert-verify: true
  sni: vle.amclubdns.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan
- delay: 2527
  name: ç¾å›½ - è–è·è¥¿ - Cloudflare, Inc. - 23
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2083
  server: 194.53.53.249
  skip-cert-verify: true
  sni: vle.amclubdns.dpdns.org
  type: trojan
  ws-opts:
    headers:
      Host: vle.amclubdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.169-0171 | 185.643MB
  password: shadowsocks
  port: 443
  server: 156.146.38.169
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.167-0172 | 182.857MB
  password: shadowsocks
  port: 443
  server: 156.146.38.167
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.168-0175 | 178.762MB
  password: shadowsocks
  port: 443
  server: 156.146.38.168
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.170-0173 | 144.325MB
  password: shadowsocks
  port: 443
  server: 156.146.38.170
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-37.19.198.236-0170 | 64.899MB
  password: shadowsocks
  port: 443
  server: 37.19.198.236
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸US-104.192.226.106-0198 | 43.877MB
  password: f8f7aCzcPKbsF8p3
  port: 989
  server: 104.192.226.106
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-37.19.198.160-0169 | 53.205MB
  password: shadowsocks
  port: 443
  server: 37.19.198.160
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.130-0185 | 47.428MB
  password: shadowsocks
  port: 443
  server: 212.102.47.130
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.131-0183 | 44.271MB
  password: shadowsocks
  port: 443
  server: 212.102.47.131
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸US-45.55.2.232-0238 | 36.921MB
  password: 2170f8
  port: 14293
  server: 45.55.2.232
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-37.19.198.243-0176 | 39.674MB
  password: shadowsocks
  port: 443
  server: 37.19.198.243
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.132-0182 | 40.079MB
  password: shadowsocks
  port: 443
  server: 212.102.47.132
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-173.244.56.9-0178 | 2.854MB
  password: shadowsocks
  port: 443
  server: 173.244.56.9
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡ºğŸ‡¸US-104.167.197.25-0273 | 1.101MB
  password: 360e21d21977dc11
  port: 57456
  server: 104.167.197.25
  type: ss
- name: ğŸ‡ºğŸ‡¸US-138.197.5.103-0307 | 0.374MB
  password: xxoo
  port: 443
  server: us.blazeppn.info
  skip-cert-verify: false
  sni: us.blazeppn.info
  type: trojan
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.129-0201 | 0.0MB
  password: shadowsocks
  port: 443
  server: 212.102.47.129
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-173.244.56.6-0177 | 47.958MB
  password: shadowsocks
  port: 443
  server: 173.244.56.6
  type: ss
- name: ğŸ‡ºğŸ‡¸US-192.3.107.252-0339 | 0.052MB
  password: 2ee85121-31de-4581-a492-eb00f606e392
  port: 443
  server: 192.3.107.252
  skip-cert-verify: false
  sni: rc8.freeguard.org
  type: trojan
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_11
  network: ws
  port: 443
  server: 172.66.47.156
  servername: wwW.oPEnsIGnAL.cOM.naynay09.Dynv6.nET
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      host: wwW.oPEnsIGnAL.cOM.naynay09.Dynv6.nET
    path: //
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_14
  network: ws
  port: 443
  server: 104.25.55.212
  servername: rayan-08.leila.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 7a80a8d9-92f9-4f0a-8352-9005a8215ab8
  ws-opts:
    headers:
      host: rayan-08.leila.dpdns.org
    path: /@filter_breaker
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_39
  network: ws
  port: 443
  server: 104.21.16.1
  servername: DD3A34A9.bPB1-1TS.PaGeS.DEV
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: cb796646-d528-4b96-9984-86dbceed95ad
  ws-opts:
    headers:
      host: DD3A34A9.bPB1-1TS.PaGeS.DEV
    path: /
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_40
  network: ws
  port: 443
  server: 172.67.68.240
  servername: rayan-fg-4.medicalhistory.filegear-sg.me
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 56497add-68ca-4500-b8e2-9f7003382bbe
  ws-opts:
    headers:
      host: rayan-fg-4.medicalhistory.filegear-sg.me
    path: /?ed=2560
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_51
  network: ws
  port: 443
  server: 172.66.47.25
  servername: GrOupYOUNeS.PAGes.DEV
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: e2d6455c-9846-4502-8394-16b8c1c07b68
  ws-opts:
    headers:
      host: GrOupYOUNeS.PAGes.DEV
    path: /telegram@v2ray_alpha/?ed=2560
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_49
  network: ws
  port: 443
  server: 172.67.66.177
  servername: rayan-roof.atena.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: db400287-fb42-441d-8a76-5624a8a96f49
  ws-opts:
    headers:
      host: rayan-roof.atena.dpdns.org
    path: /
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_42
  network: ws
  port: 443
  server: cdnjs.com
  servername: rayan-roof.atena.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: db400287-fb42-441d-8a76-5624a8a96f49
  ws-opts:
    headers:
      host: rayan-roof.atena.dpdns.org
    path: /
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_47
  network: ws
  port: 443
  server: www.vpslook.com
  servername: 64D78605.Fr-7rB.pageS.dEv
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 70f8697b-f9f3-4692-8e0a-3d1834fd76dc
  ws-opts:
    headers:
      host: 64D78605.Fr-7rB.pageS.dEv
    path: /
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_53
  network: ws
  port: 443
  server: 104.16.59.199
  servername: rayan-08.leila.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 7a80a8d9-92f9-4f0a-8352-9005a8215ab8
  ws-opts:
    headers:
      host: rayan-08.leila.dpdns.org
    path: /@rayan_config
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡ºğŸ‡¸US-94.131.21.174-0335 | 0.018MB
  password: o38yuvzSe3m5aDNpHtUPH1zGwbGEXXMDsGwVaub2SYEmHUa2WGZUjiezX3Vvva9CCzpjxYtuJLgKsSnsyKBf9ciPVba3y4o3
  port: 54075
  server: beta.mattenadene.org
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡ºğŸ‡¸US-94.131.21.174-0334 | 0.016MB
  password: o38yuvzSe3m5aDNpHtUPH1zGwbGEXXMDsGwVaub2SYEmHUa2WGZUjiezX3Vvva9CCzpjxYtuJLgKsSnsyKBf9ciPVba3y4o3
  port: 54075
  server: 94.131.21.174
  type: ss
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_19
  network: ws
  port: 443
  server: nnctwclyx.codesofun.pp.ua
  servername: nnctw.codesofun.pp.ua
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 8b9c63ff-6789-449d-e5fd-5b83fef2b440
  ws-opts:
    headers:
      host: nnctw.codesofun.pp.ua
    path: /2261acb5
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_52
  network: ws
  port: 443
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  servername: smiTs.joOjehtor.it.cOm
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 8938d63f-7dda-43be-9a1e-819adac28297
  ws-opts:
    headers:
      host: smiTs.joOjehtor.it.cOm
    path: /
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_50
  network: ws
  port: 8443
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  servername: Kz3V0zHz0P.dAsTaTsArD.oRg
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 337bf72e-bb79-4d5f-be3f-7822eb77100c
  ws-opts:
    headers:
      host: Kz3V0zHz0P.dAsTaTsArD.oRg
    path: /
- alterId: '0'
  cipher: auto
  name: ğŸ‡ºğŸ‡¸_ç¾å›½_21
  network: ws
  port: 8880
  server: www.visa.com.sg
  type: vmess
  uuid: 92e886f3-53c4-41a9-de97-a54f3abbdd9e
  ws-opts:
    headers:
      host: does-consolidated-gs-links.trycloudflare.com
    path: /
- name: ğŸ‡ºğŸ‡¸_ç¾å›½_45
  network: ws
  port: 2096
  server: ipw.gfdv54cvghhgfhgj-njhgj64.info
  servername: 0XmVfUlK85.vPbEtHoRvP002.iNfO
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 24a4aa9b-b341-4717-9d4a-00d74c2b84e0
  ws-opts:
    headers:
      host: 0XmVfUlK85.vPbEtHoRvP002.iNfO
    path: /
proxy-groups:
- name: âœˆï¸ é€‰æ‹©ä»£ç†
  proxies:
  - âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  - âš–ï¸ è´Ÿè½½å‡è¡¡
  - ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  - DIRECT
  type: select
- expected-status: 200
  include-all-proxies: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  timeout: 3000
  tolerance: 10
  type: url-test
  url: https://www.apple.com/library/test/success.html
- expected-status: 200
  include-all-proxies: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡
  strategy: consistent-hashing
  timeout: 3000
  type: load-balance
  url: https://www.apple.com/library/test/success.html
- expected-status: 200
  include-all-proxies: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  timeout: 3000
  type: select
  url: https://www.apple.com/library/test/success.html
rule-providers:
  geoip_cn_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_cn_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_cn.txt
  geoip_lan_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_lan_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_private.txt
  geosite_!cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_!cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/geolocation-!cn.txt
  geosite_@!cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@!cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_!cn.txt
  geosite_@ads:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@ads.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_ads.txt
  geosite_@cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_cn.txt
  geosite_apple:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_apple.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/apple.txt
  geosite_bing:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_bing.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/bing.txt
  geosite_cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/cn.txt
  geosite_connectivity_check:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_connectivity_check.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/connectivity-check.txt
  geosite_google:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_google.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/google.txt
  geosite_private_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_private_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/private.txt
  geosite_telegram:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/telegram.txt
  other_direct_applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/other_direct_applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  other_ssk_global_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_global_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  other_ssk_lan_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
  other_ssk_lan_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
rules:
- DOMAIN,time.apple.com,DIRECT
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN-SUFFIX,ghproxy.com,DIRECT
- DOMAIN-SUFFIX,gofile.io,DIRECT
- RULE-SET,other_direct_applications,DIRECT
- RULE-SET,other_ssk_lan_non_ip,DIRECT
- RULE-SET,geosite_private_domains,DIRECT
- RULE-SET,geosite_connectivity_check,DIRECT
- RULE-SET,geosite_@ads,REJECT
- RULE-SET,geosite_apple,DIRECT
- RULE-SET,geosite_bing,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_google,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@!cn_domains,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_ssk_global_non_ip,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@cn_domains,DIRECT
- RULE-SET,geosite_!cn,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_cn,DIRECT
- RULE-SET,geoip_lan_ip,DIRECT
- RULE-SET,other_ssk_lan_ip,DIRECT
- RULE-SET,geoip_cn_ip,DIRECT
- MATCH,âœˆï¸ é€‰æ‹©ä»£ç†
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
