allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - 94.140.14.141
  - udp://[2a10:50c0::1:ff]
  - udp://[2a10:50c0::2:ff]
  - 149.112.112.9
  - 149.112.112.112
  - udp://[2620:fe::fe]
  - udp://[2620:fe::9]
  direct-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - RULE-SET,other_ssk_lan_non_ip
  - RULE-SET,geosite_private_domains
  - RULE-SET,geosite_connectivity_check
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query#proxy&ecs=39.134.187.0/24&ecs-override=true
  - tls://1dot1dot1dot1.cloudflare-dns.com#proxy&ecs=39.134.187.0/24&ecs-override=true
  - tls://unfiltered.adguard-dns.com#proxy&ecs=39.134.187.0/24&ecs-override=true
  - tls://dns.mullvad.net#proxy&ecs=39.134.187.0/24&ecs-override=true
  - https://dns.nextdns.io/dns-query#proxy&ecs=39.134.187.0/24&ecs-override=true
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
ntp:
  enable: true
  interval: 30
  port: 123
  server: time.apple.com
  write-to-system: false
profile:
  store-fake-ip: true
  store-selected: false
proxies:
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡©ğŸ‡ªDE-46.101.245.131-0327 | 10.871MB
  password: 9RviNa4tscjcmCB408vLSg
  port: 44354
  server: 46.101.245.131
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡©ğŸ‡ªDE-147.45.178.200-0312 | 5.446MB
  password: a58fa62b4944ddbf
  port: 57456
  server: 147.45.178.200
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡©ğŸ‡ªDE-185.177.229.245-0280 | 0.38MB
  password: oXGp1+ihlfKg826H
  port: 1866
  server: 185.177.229.245
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡©ğŸ‡ªDE-84.200.91.228-0287 | 0.177MB
  password: 5ZQh4pssSk4aK1JG1XhBRg
  port: 1080
  server: 84.200.91.228
  type: ss
- alterId: 0
  cipher: auto
  name: ğŸ‡©ğŸ‡ªDE-46.165.194.96-0272 | 0.464MB
  network: ws
  port: 20086
  server: 46.165.194.96
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 01b1efee-6677-4cdb-a0f1-0f3dff2d8176
  ws-opts:
    path: /
- name: ğŸ‡©ğŸ‡ªDE-185.208.207.217-0351 | 0.028MB
  password: 2ee85121-31de-4581-a492-eb00f606e392
  port: 443
  server: 185.208.207.217
  skip-cert-verify: false
  sni: dus.freeguard.org
  type: trojan
- client-fingerprint: chrome
  name: å¾·å›½ 001
  network: ws
  password: ttfang
  port: 2096
  server: 5.10.214.216
  skip-cert-verify: true
  sni: ttfang.fange.me
  type: trojan
  ws-opts:
    headers:
      Host: ttfang.fange.me
    path: TelegramğŸ‡¨ğŸ‡³
- client-fingerprint: chrome
  name: å¾·å›½ 002
  network: ws
  password: ttfang
  port: 2096
  server: 5.10.215.216
  skip-cert-verify: true
  sni: ttfang.fange.me
  type: trojan
  ws-opts:
    headers:
      Host: ttfang.fange.me
    path: TelegramğŸ‡¨ğŸ‡³
- client-fingerprint: chrome
  name: å¾·å›½ 003
  network: ws
  password: ttfang
  port: 2096
  server: 5.175.141.216
  skip-cert-verify: true
  sni: ttfang.fange.me
  type: trojan
  ws-opts:
    headers:
      Host: ttfang.fange.me
    path: TelegramğŸ‡¨ğŸ‡³
- alpn:
  - http%2F1.1
  client-fingerprint: chrome
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 69
  network: ws
  port: 2087
  server: 104.24.90.243
  servername: JKlKL-Cx6.paGes.dev
  tls: true
  type: vless
  udp: true
  uuid: 905076f9-e34e-40b1-9e33-df06726f6336
  ws-opts:
    headers:
      Host: JKlKL-Cx6.paGes.dev
    path: /OGvsyjiasK9qcxVN/NjIuMy4xMi43Ng==?ed=2560
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 24
  network: ws
  port: 443
  server: 104.18.26.90
  servername: barayeiranmahsang.ghormehsabzi.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: e6236ebc-7334-4bed-977f-0c20bcdfcc00
  ws-opts:
    headers:
      Host: barayeiranmahsang.ghormehsabzi.dpdns.org
    path: /
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 66
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 8443
  server: 162.159.129.67
  skip-cert-verify: true
  sni: vle.amclubsvip.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubsvip.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 74
  network: ws
  password: bpb-trojan
  port: 443
  server: 104.26.4.60
  skip-cert-verify: true
  sni: zamim340.ggff.net
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: zamim340.ggff.net
    path: /tr?ed=2560
- client-fingerprint: chrome
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 88
  network: ws
  port: 443
  server: 104.26.7.214
  servername: rayan-fg-5.medicalhistory.filegear-sg.me
  tls: true
  type: vless
  udp: true
  uuid: 56497add-68ca-4500-b8e2-9f7003382bbe
  ws-opts:
    headers:
      Host: rayan-fg-5.medicalhistory.filegear-sg.me
    path: /?ed=2560
- client-fingerprint: chrome
  delay: 1234
  name: å¾·å›½ - å¾·èµ–è‰¾å¸Œ - Cloudflare, Inc. - 33
  network: ws
  password: bpb-trojan
  port: 443
  server: 172.67.70.92
  skip-cert-verify: false
  sni: zamim340.ggff.net
  type: trojan
  udp: true
  ws-opts:
    early-data-header-name: Sec-WebSocket-Protocol
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
        Gecko) Chrome/53.0.2785.143 Safari/537.36
    max-early-data: 2560
    path: /tr
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 67
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 443
  server: 162.159.133.85
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 60
  network: ws
  port: 443
  server: 162.159.152.2
  servername: vle.amclubsvip.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: d6b8011a-c725-435a-9fec-bf6d3530392c
  ws-opts:
    headers:
      Host: vle.amclubsvip.dpdns.org
    path: /
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 098
  network: ws
  password: bpb-trojan
  port: 443
  server: 162.159.152.2
  skip-cert-verify: true
  sni: zamim340.ggff.net
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: zamim340.ggff.net
    path: /tr?ed=2560
- client-fingerprint: chrome
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 089
  network: ws
  port: 443
  server: 104.25.235.104
  servername: F1.paRsa.fiLegEar-Sg.Me
  tls: true
  type: vless
  udp: true
  uuid: 8df60790-c903-4661-b85d-64c0009378e5
  ws-opts:
    headers:
      Host: F1.paRsa.fiLegEar-Sg.Me
    path: /?ed=2560
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 49
  network: ws
  password: bpb-trojan
  port: 443
  server: 162.159.153.2
  skip-cert-verify: false
  sni: zamim340.ggff.net
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: zamim340.ggff.net
    path: /tr
- client-fingerprint: randomized
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 053
  network: ws
  port: 2053
  server: 162.159.129.11
  servername: vle.amclubsapp.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: d6b8011a-c725-435a-9fec-bf6d3530392c
  ws-opts:
    headers:
      Host: vle.amclubsapp.dpdns.org
    path: /?ed=2560&PROT_TYPE=vless&NAT64=true
- client-fingerprint: randomized
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 21
  network: ws
  port: 443
  server: 162.159.133.85
  servername: vle.amclubsdns.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: d6b8011a-c725-435a-9fec-bf6d3530392c
  ws-opts:
    headers:
      Host: vle.amclubsdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=vless&NAT64=true
- client-fingerprint: randomized
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 04
  network: ws
  port: 8443
  server: 162.159.129.67
  servername: vle.amclubsdns.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: d6b8011a-c725-435a-9fec-bf6d3530392c
  ws-opts:
    headers:
      Host: vle.amclubsdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=vless&NAT64=true
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 05
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2053
  server: 162.159.129.11
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- client-fingerprint: firefox
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 10
  network: ws
  port: 443
  server: 104.21.36.57
  servername: sample.fullmargintraders.com
  tls: true
  type: vless
  udp: true
  uuid: 59171a5a-c42c-47be-aaf1-cbaefcc5a07d
  ws-opts:
    headers:
      Host: sample.fullmargintraders.com
    path: /wsv/59171a5a-c42c-47be-aaf1-cbaefcc5a07d
- client-fingerprint: random
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 76
  network: ws
  port: 443
  server: 104.26.5.134
  servername: 007.xingfu.qzz.io
  tls: true
  type: vless
  udp: true
  uuid: d88937d0-ce43-4bf8-9df6-d632810ba9ff
  ws-opts:
    headers:
      Host: 007.xingfu.qzz.io
    path: /
- client-fingerprint: randomized
  name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 41 #2'
  network: ws
  port: 2087
  server: 104.25.254.4
  servername: vle.amclubsdns.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: d6b8011a-c725-435a-9fec-bf6d3530392c
  ws-opts:
    headers:
      Host: vle.amclubsdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=vless&NAT64=true
- name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 12 #2'
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2087
  server: 104.25.254.4
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- alterId: 0
  cipher: auto
  country: ğŸ‡®ğŸ‡·IR
  delay: 2732
  h2-opts: {}
  http-opts: {}
  name: å¾·å›½ - Frankfurt Am Main - Hetzner Online AG - 2
  network: tcp
  port: 443
  server: 37.202.247.4
  server_url: dl01.armod.top
  skip-cert-verify: true
  type: vmess
  uuid: cd11391b-9f7a-4478-b624-3a1d5d81d426
- auth: a503efc7-b681-466f-be23-434483b2a07b
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 26
  password: a503efc7-b681-466f-be23-434483b2a07b
  port: 22155
  server: 213.108.198.123
  server_url: hsdg.huasuan666.top
  skip-cert-verify: true
  sni: hsdg.huasuan666.top
  type: hysteria2
  udp: true
- http-opts:
    headers:
      Host:
      - filimo.com
    method: GET
    path:
    - /
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 54
  network: http
  port: 2083
  server: 109.94.164.184
  server_url: germany1.premiumiran.top
  servername: filimo.com
  tls: false
  type: vless
  udp: true
  uuid: 59290e80-153b-4d2c-8a5b-8a1922608832
- auth: 1acd1a12-bc74-452a-999f-539f4d492c6d
  name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 21 #2'
  password: 1acd1a12-bc74-452a-999f-539f4d492c6d
  port: 22158
  server: 213.108.198.123
  server_url: hsfg.huasuan666.top
  skip-cert-verify: true
  sni: hsfg.huasuan666.top
  type: hysteria2
  udp: true
proxy-groups:
- name: âœˆï¸ é€‰æ‹©ä»£ç†
  proxies:
  - âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  - âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlåŒä¸€èŠ‚ç‚¹
  - âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlä¸åŒèŠ‚ç‚¹
  - ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  type: select
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  timeout: 3000
  tolerance: 10
  type: url-test
  url: https://cp.cloudflare.com/generate_204
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlåŒä¸€èŠ‚ç‚¹
  strategy: consistent-hashing
  timeout: 3000
  type: load-balance
  url: https://cp.cloudflare.com/generate_204
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlä¸åŒèŠ‚ç‚¹
  strategy: round-robin
  timeout: 3000
  type: load-balance
  url: https://cp.cloudflare.com/generate_204
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  timeout: 3000
  type: select
  url: https://cp.cloudflare.com/generate_204
rule-providers:
  geoip_cn_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_cn_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_cn.txt
  geoip_lan_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_lan_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_private.txt
  geoip_telegram_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_telegram.txt
  geosite_!cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_!cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/geolocation-!cn.txt
  geosite_@!cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@!cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_!cn.txt
  geosite_@ads:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@ads.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_ads.txt
  geosite_@cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_cn.txt
  geosite_apple:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_apple.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/apple.txt
  geosite_bing:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_bing.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/bing.txt
  geosite_cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/cn.txt
  geosite_connectivity_check:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_connectivity_check.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/connectivity-check.txt
  geosite_google:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_google.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/google.txt
  geosite_private_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_private_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/private.txt
  geosite_telegram:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/telegram.txt
  loy_gfw:
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/loy_gfw.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt
  loy_reject:
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/loy_reject.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/reject-list.txt
  other_direct_applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/other_direct_applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  other_ssk_global_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_global_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  other_ssk_lan_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
  other_ssk_lan_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
  self_gemini_site:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/self_gemini_site.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/clash_config_auto_build@refs/heads/main/rules/gemini_rules.yaml
rules:
- RULE-SET,loy_reject,REJECT
- RULE-SET,geosite_@ads,REJECT
- DOMAIN-SUFFIX,dahuatech.com,DIRECT
- DOMAIN,time.apple.com,DIRECT
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN-SUFFIX,ghproxy.com,DIRECT
- DOMAIN-SUFFIX,facefusion.io,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,anaconda.com,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,modelscope.cn,DIRECT
- DOMAIN-SUFFIX,akfamily.xyz,DIRECT
- DOMAIN,shared.cdn.queniuqe.com,DIRECT
- DOMAIN-SUFFIX,1fichier.com,DIRECT
- PROCESS-NAME,Telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,v2ex.com,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-KEYWORD,alibaba-cn,DIRECT
- RULE-SET,other_direct_applications,DIRECT
- RULE-SET,other_ssk_lan_non_ip,DIRECT
- RULE-SET,geosite_private_domains,DIRECT
- RULE-SET,geosite_connectivity_check,DIRECT
- RULE-SET,self_gemini_site,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_apple,DIRECT
- RULE-SET,geosite_bing,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_google,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,loy_gfw,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_ssk_global_non_ip,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@cn_domains,DIRECT
- RULE-SET,geosite_!cn,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@!cn_domains,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_cn,DIRECT
- RULE-SET,geoip_lan_ip,DIRECT,no-resolve
- RULE-SET,other_ssk_lan_ip,DIRECT,no-resolve
- RULE-SET,geoip_telegram_ip,âœˆï¸ é€‰æ‹©ä»£ç†,no-resolve
- RULE-SET,geoip_cn_ip,DIRECT,no-resolve
- MATCH,âœˆï¸ é€‰æ‹©ä»£ç†
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
