allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - 94.140.14.141
  - udp://[2a10:50c0::1:ff]
  - udp://[2a10:50c0::2:ff]
  - 149.112.112.9
  - 149.112.112.112
  - udp://[2620:fe::fe]
  - udp://[2620:fe::9]
  direct-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - RULE-SET,other_ssk_lan_non_ip
  - RULE-SET,geosite_private_domains
  - RULE-SET,geosite_connectivity_check
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query#proxy&ecs=39.134.187.0/24&ecs-override=true
  - tls://1dot1dot1dot1.cloudflare-dns.com#proxy&ecs=39.134.187.0/24&ecs-override=true
  - tls://unfiltered.adguard-dns.com#proxy&ecs=39.134.187.0/24&ecs-override=true
  - tls://dns.mullvad.net#proxy&ecs=39.134.187.0/24&ecs-override=true
  - https://dns.nextdns.io/dns-query#proxy&ecs=39.134.187.0/24&ecs-override=true
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
ntp:
  enable: true
  interval: 30
  port: 123
  server: time.apple.com
  write-to-system: false
profile:
  store-fake-ip: true
  store-selected: false
proxies:
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-37.19.198.243-0205 | 98.05MB
  password: shadowsocks
  port: 443
  server: 37.19.198.243
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-37.19.198.160-0204 | 65.1MB
  password: shadowsocks
  port: 443
  server: 37.19.198.160
  type: ss
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡ºğŸ‡¸US-64.74.163.130-0212 | 58.711MB
  password: f8f7aCzcPKbsF8p3
  port: 990
  server: 64.74.163.130
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.170-0208 | 110.394MB
  password: shadowsocks
  port: 443
  server: 156.146.38.170
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.167-0207 | 101.668MB
  password: shadowsocks
  port: 443
  server: 156.146.38.167
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.168-0210 | 106.533MB
  password: shadowsocks
  port: 443
  server: 156.146.38.168
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-156.146.38.169-0209 | 117.87MB
  password: shadowsocks
  port: 443
  server: 156.146.38.169
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-173.244.56.9-0213 | 72.456MB
  password: shadowsocks
  port: 443
  server: 173.244.56.9
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.131-0258 | 85.14MB
  password: shadowsocks
  port: 443
  server: 212.102.47.131
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.132-0253 | 66.388MB
  password: shadowsocks
  port: 443
  server: 212.102.47.132
  type: ss
- cipher: aes-128-gcm
  name: ğŸ‡ºğŸ‡¸US-212.102.47.130-0215 | 56.188MB
  password: shadowsocks
  port: 443
  server: 212.102.47.130
  type: ss
- cipher: rc4-md5
  name: ğŸ‡ºğŸ‡¸US-23.251.121.242-0367 | 79.388MB
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 23.251.121.242
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡ºğŸ‡¸US-104.192.226.106-0239 | 31.44MB
  password: f8f7aCzcPKbsF8p3
  port: 989
  server: 104.192.226.106
  type: ss
- name: ğŸ‡ºğŸ‡¸US-192.3.107.252-0349 | 0.169MB
  password: 2ee85121-31de-4581-a492-eb00f606e392
  port: 443
  server: 192.3.107.252
  skip-cert-verify: false
  sni: rc8.freeguard.org
  type: trojan
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸US-137.175.124.167-0300 | 7.743MB
  network: ws
  port: 20086
  server: 137.175.124.167
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b4bce500-11fe-4f8f-a344-01ac247af9bd
  ws-opts:
    path: /
- name: ğŸ‡ºğŸ‡¸US-198.46.152.83-5029 | 0.153MB
  password: 2ee85121-31de-4581-a492-eb00f606e392
  port: 443
  server: 198.46.152.83
  skip-cert-verify: false
  sni: sj3.freeguard.org
  type: trojan
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸US-206.206.80.227-0351 | 0.068MB
  network: ws
  port: 20086
  server: 206.206.80.227
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 0abb7b9e-81ba-4336-8ca7-056866032ff3
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  fingerprint: ''
  name: ğŸ‡ºğŸ‡¸_US_ç¾å›½->ğŸ‡ªğŸ‡¸_ES_è¥¿ç­ç‰™_1
  network: tcp
  port: 443
  server: 38.60.134.249
  sni: ''
  type: vmess
  uuid: beb28159-7f4c-4c09-9313-6283515f150b
- alterId: 0
  cipher: auto
  fingerprint: ''
  name: ğŸ‡ºğŸ‡¸_US_ç¾å›½->ğŸ‡ªğŸ‡¸_ES_è¥¿ç­ç‰™
  network: tcp
  port: 443
  server: 38.54.59.237
  sni: ''
  type: vmess
  uuid: 5ac807d5-42c9-4b97-9567-478e61dab696
- cipher: rc4-md5
  name: SSR-ç¾å›½-NFè§£é”è‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-107.151.182.253:8080
  obfs: plain
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  protocol: origin
  server: 107.151.182.253
  type: ssr
- cipher: rc4-md5
  name: ğŸ‡ºğŸ‡¸US-107.151.182.253-0213 | 54.355MB
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 107.151.182.253
  type: ss
- name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 544 #2'
  network: ws
  password: slch2024
  port: 443
  server: 104.18.2.150
  skip-cert-verify: true
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /
- client-fingerprint: chrome
  name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 269 #2'
  network: tcp
  port: 34045
  reality-opts:
    public-key: cDaDzPr3PlS3NM8lreHZbdo-Mhqz8vMBzMSkHXhGIUA
    short-id: e8ab71d0
  server: 172.233.200.247
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  tls: true
  type: vless
  udp: true
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
- name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 253 #2'
  network: ws
  password: slch2024
  port: 2083
  server: 104.18.3.26
  server_url: www.visaeurope.ch
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /?ed=2560
- name: ğŸ‡ºğŸ‡¸ ç¾å›½ 700
  network: ws
  password: slch2024
  port: 8443
  server: 104.18.2.108
  skip-cert-verify: true
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /
- name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 351 #2'
  network: ws
  password: slch2024
  port: 2053
  server: 104.18.4.250
  server_url: www.visa.com.tw
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /?ed=2560
- client-fingerprint: chrome
  name: ğŸ‡ºğŸ‡¸ ç¾å›½ 006
  network: tcp
  port: 34045
  reality-opts:
    public-key: cDaDzPr3PlS3NM8lreHZbdo-Mhqz8vMBzMSkHXhGIUA
    short-id: e8ab71d0
  server: 172.233.201.93
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  tls: true
  type: vless
  udp: true
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
- name: ğŸ‡ºğŸ‡¸ ç¾å›½ 696
  network: ws
  password: slch2024
  port: 2096
  server: 104.18.15.201
  server_url: www.visasoutheasteurope.com
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /?ed=2560
- name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 812 #2'
  network: ws
  password: slch2024
  port: 443
  server: 104.18.3.150
  skip-cert-verify: true
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /
- name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 276 #2'
  network: ws
  password: slch2024
  port: 2087
  server: 104.18.13.51
  server_url: www.visa.com.br
  sni: ocost-dy.wmlefl.cc
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: ocost-dy.wmlefl.cc
    path: /?ed=2560
- alterId: '64'
  cipher: auto
  name: 'ğŸ‡ºğŸ‡¸_ç¾å›½_3 #2 #2'
  network: tcp
  port: 30002
  server: 38.12.83.217
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: ğŸ‡ºğŸ‡¸US-138.197.5.103-0206 | 0.267MB
  password: xxoo
  port: 443
  server: 138.197.5.103
  server_url: us.blazeppn.info
  skip-cert-verify: false
  sni: us.blazeppn.info
  type: trojan
- client-fingerprint: chrome
  name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 302 #2'
  network: tcp
  port: 34045
  reality-opts:
    public-key: cDaDzPr3PlS3NM8lreHZbdo-Mhqz8vMBzMSkHXhGIUA
    short-id: e8ab71d0
  server: 46.17.107.16
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  tls: true
  type: vless
  udp: true
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
- client-fingerprint: chrome
  name: ğŸ‡ºğŸ‡¸ ç¾å›½ 285
  network: tcp
  port: 34045
  reality-opts:
    public-key: cDaDzPr3PlS3NM8lreHZbdo-Mhqz8vMBzMSkHXhGIUA
    short-id: e8ab71d0
  server: 172.233.140.201
  servername: visit-this-invitation-link-to-join-tg-enkelte-notif.ekt.me
  tls: true
  type: vless
  udp: true
  uuid: d8dd94fd-540e-461d-b5d4-acebef02c22a
- alpn:
  - h3
  auth-str: dongtaiwang.com
  auth_str: dongtaiwang.com
  down: 55 Mbps
  name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 069 #2'
  port: 37872
  protocol: udp
  server: 108.181.24.77
  skip-cert-verify: true
  sni: apple.com
  type: hysteria
  udp: true
  up: 11 Mbps
- alpn:
  - h3
  auth-str: dongtaiwang.com
  auth_str: dongtaiwang.com
  down: 100
  name: 'ğŸ‡ºğŸ‡¸ ç¾å›½ 544 #3'
  port: 38845
  protocol: udp
  server: 208.87.243.151
  skip-cert-verify: true
  sni: www.bing.com
  type: hysteria
  udp: true
  up: 100
- alterId: 0
  cipher: auto
  country: ğŸ‡ºğŸ‡¸US
  delay: 1427
  h2-opts: {}
  http-opts: {}
  name: ç¾å›½ - æ—§é‡‘å±± - Newserverlife LLC - 2
  network: ws
  port: 8443
  server: 38.107.236.166
  server_url: 3h-unitedstates3.09vpn.com
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: 0c17318b-d8e7-4816-a6a2-ab873a3bcc8b
  ws-opts:
    path: /vmess/
- alterId: 0
  cipher: auto
  name: ğŸ‡©ğŸ‡°_DK_ä¸¹éº¦->ğŸ‡ºğŸ‡¸_US_ç¾å›½_1
  network: ws
  port: 80
  server: 195.85.59.10
  server_url: pubg.ac
  type: vmess
  uuid: 56c852c2-9517-4c13-ae18-bf0bee41706a
  ws-opts:
    headers:
      host: cdn-node-oss-99.paofu.de
    path: /profile/telegram@ssrsub
- name: ğŸ‡©ğŸ‡°_DK_ä¸¹éº¦->ğŸ‡ºğŸ‡¸_US_ç¾å›½
  network: ws
  password: 56c852c2-9517-4c13-ae18-bf0bee41706a
  port: 8443
  server: 195.85.59.99
  server_url: fastcup.net
  sni: cdn-node-oss-99.paofu.de
  type: trojan
  udp: true
  ws-opts:
    headers:
      host: cdn-node-oss-99.paofu.de
    path: /profile/telegram@ssrsub
proxy-groups:
- name: âœˆï¸ é€‰æ‹©ä»£ç†
  proxies:
  - âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  - âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlåŒä¸€èŠ‚ç‚¹
  - âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlä¸åŒèŠ‚ç‚¹
  - ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  type: select
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  timeout: 3000
  tolerance: 10
  type: url-test
  url: https://cp.cloudflare.com/generate_204
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlåŒä¸€èŠ‚ç‚¹
  strategy: consistent-hashing
  timeout: 3000
  type: load-balance
  url: https://cp.cloudflare.com/generate_204
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡-åŒä¸€urlä¸åŒèŠ‚ç‚¹
  strategy: round-robin
  timeout: 3000
  type: load-balance
  url: https://cp.cloudflare.com/generate_204
- expected-status: 204
  include-all: true
  include-all-proxies: true
  interval: 120
  lazy: true
  max-failed-times: 2
  name: ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  timeout: 3000
  type: select
  url: https://cp.cloudflare.com/generate_204
rule-providers:
  geoip_cn_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_cn_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_cn.txt
  geoip_lan_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_lan_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_private.txt
  geoip_telegram_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_telegram.txt
  geosite_!cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_!cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/geolocation-!cn.txt
  geosite_@!cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@!cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_!cn.txt
  geosite_@ads:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@ads.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_ads.txt
  geosite_@cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_cn.txt
  geosite_apple:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_apple.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/apple.txt
  geosite_bing:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_bing.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/bing.txt
  geosite_cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/cn.txt
  geosite_connectivity_check:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_connectivity_check.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/connectivity-check.txt
  geosite_google:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_google.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/google.txt
  geosite_private_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_private_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/private.txt
  geosite_telegram:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/telegram.txt
  loy_gfw:
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/loy_gfw.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/gfw.txt
  loy_reject:
    behavior: domain
    format: text
    interval: 86400
    path: ./ruleset/loy_reject.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/reject-list.txt
  other_direct_applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/other_direct_applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  other_ssk_global_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_global_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  other_ssk_lan_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
  other_ssk_lan_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
  self_gemini_site:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/self_gemini_site.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/clash_config_auto_build@refs/heads/main/rules/gemini_rules.yaml
rules:
- RULE-SET,loy_reject,REJECT
- RULE-SET,geosite_@ads,REJECT
- DOMAIN-SUFFIX,dahuatech.com,DIRECT
- DOMAIN,time.apple.com,DIRECT
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN-SUFFIX,ghproxy.com,DIRECT
- DOMAIN-SUFFIX,facefusion.io,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,anaconda.com,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,modelscope.cn,DIRECT
- DOMAIN-SUFFIX,akfamily.xyz,DIRECT
- DOMAIN,shared.cdn.queniuqe.com,DIRECT
- DOMAIN-SUFFIX,1fichier.com,DIRECT
- PROCESS-NAME,Telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,v2ex.com,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-KEYWORD,alibaba-cn,DIRECT
- DOMAIN-KEYWORD,cloudflare,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_direct_applications,DIRECT
- RULE-SET,other_ssk_lan_non_ip,DIRECT
- RULE-SET,geosite_private_domains,DIRECT
- RULE-SET,geosite_connectivity_check,DIRECT
- RULE-SET,self_gemini_site,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_apple,DIRECT
- RULE-SET,geosite_bing,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_google,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,loy_gfw,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_ssk_global_non_ip,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@cn_domains,DIRECT
- RULE-SET,geosite_!cn,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@!cn_domains,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_cn,DIRECT
- RULE-SET,geoip_lan_ip,DIRECT,no-resolve
- RULE-SET,other_ssk_lan_ip,DIRECT,no-resolve
- RULE-SET,geoip_telegram_ip,âœˆï¸ é€‰æ‹©ä»£ç†,no-resolve
- RULE-SET,geoip_cn_ip,DIRECT,no-resolve
- MATCH,âœˆï¸ é€‰æ‹©ä»£ç†
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
