allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - 94.140.14.141
  - udp://[2a10:50c0::1:ff]
  - udp://[2a10:50c0::2:ff]
  - 149.112.112.9
  - 149.112.112.112
  - udp://[2620:fe::fe]
  - udp://[2620:fe::9]
  direct-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - RULE-SET,other_ssk_lan_non_ip
  - RULE-SET,geosite_private_domains
  - RULE-SET,geosite_connectivity_check
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://1dot1dot1dot1.cloudflare-dns.com
  - tls://unfiltered.adguard-dns.com
  - tls://dns.mullvad.net
  - https://dns.nextdns.io/dns-query
  proxy-server-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
ntp:
  enable: true
  interval: 30
  port: 123
  server: time.apple.com
  write-to-system: false
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: chacha20-ietf-poly1305
  name: SS-å¾·å›½-NFè§£é”æ¾³å¤§åˆ©äºšè‡ªåˆ¶å‰§-ChatGPT-TikTok-185.177.229.245:1866
  password: oXGp1+ihlfKg826H
  port: 1866
  server: 185.177.229.245
  type: ss
- cipher: chacha20-ietf-poly1305
  name: SS-å¾·å›½-NFè§£é”å¾·å›½åœ°åŒºéè‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-46.101.245.131:44354
  password: 9RviNa4tscjcmCB408vLSg
  port: 44354
  server: 46.101.245.131
  type: ss
- cipher: chacha20-ietf-poly1305
  name: SS-æ–¯æ´›æ–‡å°¼äºš-NFè§£é”å¾·å›½åœ°åŒºéè‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-45.144.54.33:34803
  password: LiHQX9cDbdooBHlIg0eiqQ
  port: 34803
  server: 45.144.54.33
  type: ss
- cipher: chacha20-ietf-poly1305
  name: SS-å¾·å›½-NFè§£é”å¾·å›½åœ°åŒºéè‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-147.45.178.200:57456
  password: a58fa62b4944ddbf
  port: 57456
  server: 147.45.178.200
  type: ss
- cipher: rc4-md5
  name: ğŸ‡©ğŸ‡ªDE-193.108.119.230-0307 | 14.127MB
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 193.108.119.230
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4900 | 1.213MB
  password: cp8pRSUAyLhTfVWH
  port: 9064
  server: 80.92.204.106
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-0325 | 0.974MB
  password: TN2YqghxeFDKZfLU
  port: 9037
  server: 80.92.204.106
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4849 | 0.431MB
  password: a3GFYt36Sm82Vys9
  port: 9000
  server: 80.92.204.106
  type: ss
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 01
  network: ws
  port: 443
  server: 104.24.71.251
  servername: hai.gdz.buzz
  tls: true
  type: vless
  udp: true
  uuid: 8f7fe273-e06d-47d5-9deb-d7b3c95dc573
  ws-opts:
    headers:
      Host: hai.gdz.buzz
    path: /
- client-fingerprint: random
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 24
  network: ws
  port: 2087
  server: 104.24.135.129
  servername: fandouhuayuan.pages.dev
  tls: true
  type: vless
  udp: true
  uuid: 7b5ea382-cbc6-4169-9f88-8200ca80c31a
  ws-opts:
    headers:
      Host: fandouhuayuan.pages.dev
    path: /?ed=2560
- alterId: 0
  cipher: ''
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨34
  network: ws
  port: 8880
  server: 167.68.5.177
  skip-cert-verify: true
  tfo: false
  tls: false
  type: vless
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /freecodesè˜‡å°æª¸ | è¯æ±é›»è¨Š | è§£é–Netflix
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨30
  network: ws
  port: 8443
  server: 104.26.7.89
  servername: brmahasang.ahaysiahzangi.dpdns.org
  skip-cert-verify: true
  sni: brmahasang.ahaysiahzangi.dpdns.org
  tfo: false
  tls: true
  type: vless
  uuid: f5cf098f-5143-440f-a490-7fc24ff27fb0
  ws-opts:
    headers:
      Host: brmahasang.ahaysiahzangi.dpdns.org
    path: /?ed=2560
- alpn:
  - http%2F1.1
  alterId: 0
  cipher: ''
  client-fingerprint: randomized
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨29
  network: ws
  port: 443
  server: 104.17.182.58
  servername: frieren.albedo.ddns-ip.net
  skip-cert-verify: true
  sni: frieren.albedo.ddns-ip.net
  tfo: false
  tls: true
  type: vless
  uuid: c1601a96-febd-4baa-8fe3-17ca8f4121bd
  ws-opts:
    headers:
      Host: frieren.albedo.ddns-ip.net
    path: /proxyip=ayaka.shorekeeper.ir
- client-fingerprint: randomized
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 42
  network: ws
  port: 443
  server: 104.17.71.31
  servername: vle.amclubsdns.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: d6b8011a-c725-435a-9fec-bf6d3530392c
  ws-opts:
    headers:
      Host: vle.amclubsdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=vless&NAT64=true
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨33
  network: ws
  port: 443
  server: 104.19.173.68
  servername: rayan-fg-7.mohammad-janam.filegear-sg.me
  skip-cert-verify: true
  sni: rayan-fg-7.mohammad-janam.filegear-sg.me
  tfo: false
  tls: true
  type: vless
  uuid: e97a0128-4785-4323-a2a5-dd01ce49d359
  ws-opts:
    headers:
      Host: rayan-fg-7.mohammad-janam.filegear-sg.me
    path: /?ed=2560
- client-fingerprint: random
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 04
  network: ws
  port: 443
  server: 172.64.68.58
  servername: hai.gdz.buzz
  tls: true
  type: vless
  udp: true
  uuid: 8f7fe273-e06d-47d5-9deb-d7b3c95dc573
  ws-opts:
    headers:
      Host: hai.gdz.buzz
    path: /?ed=2560
- name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 01 #2'
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2053
  server: 162.159.129.11
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- client-fingerprint: random
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 07
  network: ws
  port: 443
  server: 104.24.230.10
  servername: jack.jack-cq.click
  tls: true
  type: vless
  udp: true
  uuid: 72982133-27fb-46fc-9061-61113e77e201
  ws-opts:
    headers:
      Host: jack.jack-cq.click
    path: /?ed=2560
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 06
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 443
  server: 162.159.133.85
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 05 #2'
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2087
  server: 104.25.254.4
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨10
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2053
  server: 103.160.204.26
  servername: vle.amclubdns.dpdns.org
  skip-cert-verify: true
  sni: vle.amclubdns.dpdns.org
  type: trojan
  ws-opts:
    headers:
      Host: vle.amclubdns.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨21
  network: tcp
  port: 443
  reality-opts:
    public-key: RW2LSBmmSe02gQ2e4OGfNmggZbuO4trpafPiNqVEajs
    short-id: e0b8e166
  server: 5.34.214.154
  servername: ign.com
  skip-cert-verify: true
  sni: ign.com
  tfo: false
  tls: true
  type: vless
  uuid: fa92e9cd-b5be-4e00-8fc4-4543012d1fd0
- alterId: 0
  cipher: auto
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨24
  port: 43585
  server: 185.142.53.63
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 2babf34a-16f5-4e38-a885-738fdfc8eabf
- alterId: 0
  cipher: ''
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨20
  network: tcp
  port: 13305
  server: 193.238.153.85
  skip-cert-verify: true
  tfo: false
  tls: false
  type: vless
  uuid: afdb6e6e-3145-4284-c15a-0a38030a8129
- auth: 0cb527d9-6117-4bcf-a52b-1704b3458cef
  fast-open: false
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨60
  password: 0cb527d9-6117-4bcf-a52b-1704b3458cef
  port: 44594
  server: 185.126.255.78
  servername: dxobg4azmk.gafnode.sbs
  skip-cert-verify: true
  sni: dxobg4azmk.gafnode.sbs
  type: hysteria2
- alterId: 0
  cipher: ''
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨2
  network: ws
  port: 443
  server: 108.162.194.231
  servername: rs-sg4.lzjnb.shop
  skip-cert-verify: true
  sni: rs-sg4.lzjnb.shop
  tfo: false
  tls: true
  type: vless
  uuid: b7f8c66b-40f0-4160-8b88-76a482e2b593
  ws-opts:
    headers:
      Host: rs-sg4.lzjnb.shop
    path: /lzj
- alterId: 0
  cipher: ''
  client-fingerprint: random
  flow: xtls-rprx-vision
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨23
  network: tcp
  port: 16106
  reality-opts:
    public-key: FnkrwrjQqktvwxPvLn7KyWZIq8bUAvVaeCrI_VhAZ34
    short-id: 3b6239cf6fd84dd3
  server: 185.250.181.128
  servername: yahoo.com
  skip-cert-verify: true
  sni: yahoo.com
  tfo: false
  tls: true
  type: vless
  uuid: aa1aac84-6a86-41b9-bd34-1a036e06976f
proxy-groups:
- name: âœˆï¸ é€‰æ‹©ä»£ç†
  proxies:
  - âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  - âš–ï¸ è´Ÿè½½å‡è¡¡
  - ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  - DIRECT
  type: select
- expected-status: 200
  include-all: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  timeout: 3000
  tolerance: 10
  type: url-test
  url: https://www.apple.com/library/test/success.html
- expected-status: 200
  include-all: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡
  strategy: consistent-hashing
  timeout: 3000
  type: load-balance
  url: https://www.apple.com/library/test/success.html
- expected-status: 200
  include-all: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  timeout: 3000
  type: select
  url: https://www.apple.com/library/test/success.html
rule-providers:
  geoip_cn_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_cn_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_cn.txt
  geoip_lan_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_lan_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_private.txt
  geosite_!cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_!cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/geolocation-!cn.txt
  geosite_@!cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@!cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_!cn.txt
  geosite_@ads:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@ads.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_ads.txt
  geosite_@cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_cn.txt
  geosite_apple:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_apple.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/apple.txt
  geosite_bing:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_bing.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/bing.txt
  geosite_cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/cn.txt
  geosite_connectivity_check:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_connectivity_check.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/connectivity-check.txt
  geosite_google:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_google.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/google.txt
  geosite_private_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_private_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/private.txt
  geosite_telegram:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/telegram.txt
  other_direct_applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/other_direct_applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  other_ssk_global_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_global_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  other_ssk_lan_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
  other_ssk_lan_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
rules:
- DOMAIN,time.apple.com,DIRECT
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN-SUFFIX,ghproxy.com,DIRECT
- DOMAIN-SUFFIX,gofile.io,DIRECT
- DOMAIN-SUFFIX,facefusion.io,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,anaconda.com,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_direct_applications,DIRECT
- RULE-SET,other_ssk_lan_non_ip,DIRECT
- RULE-SET,geosite_private_domains,DIRECT
- RULE-SET,geosite_connectivity_check,DIRECT
- RULE-SET,geosite_@ads,REJECT
- RULE-set,geosite_apple,DIRECT
- RULE-SET,geosite_bing,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_google,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@!cn_domains,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_ssk_global_non_ip,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@cn_domains,DIRECT
- RULE-SET,geosite_!cn,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_cn,DIRECT
- RULE-SET,geoip_lan_ip,DIRECT
- RULE-SET,other_ssk_lan_ip,DIRECT
- RULE-SET,geoip_cn_ip,DIRECT
- MATCH,âœˆï¸ é€‰æ‹©ä»£ç†
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
