allow-lan: true
dns:
  default-nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - 94.140.14.141
  - udp://[2a10:50c0::1:ff]
  - udp://[2a10:50c0::2:ff]
  - 149.112.112.9
  - 149.112.112.112
  - udp://[2620:fe::fe]
  - udp://[2620:fe::9]
  direct-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  direct-nameserver-follow-policy: false
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.tvkuai.com
  - RULE-SET,other_ssk_lan_non_ip
  - RULE-SET,geosite_private_domains
  - RULE-SET,geosite_connectivity_check
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  ipv6: true
  nameserver:
  - https://[2001:4860:4860::64]/dns-query
  - tls://1dot1dot1dot1.cloudflare-dns.com
  - tls://unfiltered.adguard-dns.com
  - tls://dns.mullvad.net
  - https://dns.nextdns.io/dns-query
  proxy-server-nameserver:
  - https://1.12.12.12/dns-query
  - https://223.5.5.5/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
global-client-fingerprint: firefox
ipv6: true
mixed-port: 7890
ntp:
  enable: true
  interval: 30
  port: 123
  server: time.apple.com
  write-to-system: false
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: chacha20-ietf-poly1305
  name: SS-å¾·å›½-NFè§£é”å¾·å›½åœ°åŒºéè‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-147.45.178.200:57456
  password: a58fa62b4944ddbf
  port: 57456
  server: 147.45.178.200
  type: ss
- cipher: chacha20-ietf-poly1305
  name: SS-æ–¯æ´›æ–‡å°¼äºš-NFè§£é”å¾·å›½åœ°åŒºéè‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-45.144.54.33:34803
  password: LiHQX9cDbdooBHlIg0eiqQ
  port: 34803
  server: 45.144.54.33
  type: ss
- cipher: chacha20-ietf-poly1305
  name: SS-å¾·å›½-NFè§£é”å¾·å›½åœ°åŒºéè‡ªåˆ¶å‰§-ChatGPT-TikTok-YouTube-46.101.245.131:44354
  password: 9RviNa4tscjcmCB408vLSg
  port: 44354
  server: 46.101.245.131
  type: ss
- cipher: chacha20-ietf-poly1305
  name: SS-å¾·å›½-NFè§£é”æ¾³å¤§åˆ©äºšè‡ªåˆ¶å‰§-ChatGPT-TikTok-185.177.229.245:1866
  password: oXGp1+ihlfKg826H
  port: 1866
  server: 185.177.229.245
  type: ss
- name: ğŸ‡©ğŸ‡ª_å¾·å›½_1
  network: ws
  port: 2053
  server: 141.94.70.243
  servername: ax1.ylka.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  ws-opts:
    headers:
      host: ax1.ylka.dpdns.org
    path: /?ed=2560
- name: ğŸ‡©ğŸ‡ª_å¾·å›½_3
  network: ws
  port: 8443
  server: 91.107.159.178
  servername: zx1.ylka.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  ws-opts:
    headers:
      host: zx1.ylka.dpdns.org
    path: /?ed=2560
- name: ğŸ‡©ğŸ‡ª_å¾·å›½_5
  network: ws
  port: 443
  server: 91.107.254.116
  servername: ax1.ylka.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  ws-opts:
    headers:
      host: ax1.ylka.dpdns.org
    path: /?ed=2560
- name: ğŸ‡©ğŸ‡ª_å¾·å›½_6
  network: ws
  port: 443
  server: 91.107.189.217
  servername: zx1.ylka.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  ws-opts:
    headers:
      host: zx1.ylka.dpdns.org
    path: /?ed=2560
- name: ğŸ‡©ğŸ‡ª_å¾·å›½_4
  network: ws
  port: 443
  server: 91.107.251.232
  servername: zx1.ylka.dpdns.org
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 06e4425e-a8cb-4b63-929f-2105604ab0a9
  ws-opts:
    headers:
      host: zx1.ylka.dpdns.org
    path: /?ed=2560
- alterId: 0
  cipher: auto
  name: ğŸ‡©ğŸ‡ªDE-91.99.153.39-7386 | 38.037MB
  network: ws
  port: 39130
  server: 91.99.153.39
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 985af489-fb16-491a-813c-fdd91b6b06ee
  ws-opts:
    headers:
      Host: panel.arushasoft.com
    path: /
- alterId: 0
  cipher: auto
  name: ğŸ‡©ğŸ‡ªDE-171.22.31.187-013
  network: tcp
  port: 35879
  server: 171.22.31.187
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: deff1354-92b9-42cc-8ee6-46dead4e1c5d
  ws-headers:
    Host: 171.22.31.187
  ws-path: /
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 13
  network: ws
  password: bpb-trojan
  port: 443
  server: 104.26.4.60
  sni: zamim340.ggff.net
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: zamim340.ggff.net
    path: /tr?ed=2560
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡©ğŸ‡ª_DE_å¾·å›½_1@6
  password: QCXDxuDlTTMD7jtgHUjIoj
  port: 8080
  server: 45.87.175.166
  type: ss
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 50
  network: tcp
  port: 44774
  server: 46.29.34.205
  tls: false
  type: vless
  udp: true
  uuid: 20447cea-457f-426c-88ec-3208588250af
- alterId: 0
  cipher: auto
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 52
  port: 22947
  server: 46.29.34.205
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: d7291fc4-1702-4826-8fe1-ab301b1c8f82
- client-fingerprint: chrome
  name: ğŸ‡©ğŸ‡ª å¾·å›½ 34
  network: ws
  port: 443
  server: 104.24.197.20
  servername: rayan-roof.atena.dpdns.org
  tls: true
  type: vless
  udp: true
  uuid: db400287-fb42-441d-8a76-5624a8a96f49
  ws-opts:
    headers:
      Host: rayan-roof.atena.dpdns.org
    path: /
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 37
  network: ws
  port: 8880
  server: 104.16.69.36
  tls: false
  type: vless
  udp: true
  uuid: 02811288-9ef3-42ef-86db-d9b1399c1a59
  ws-opts:
    headers:
      Host: vghavi32.ip-ddns.com
    path: /7YVyoVNnbaVzgl6D?ed=2560
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 02
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 8443
  server: 162.159.129.67
  skip-cert-verify: true
  sni: vle.amclubsvip.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubsvip.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- alterId: 0
  cipher: ''
  encryption: none
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨14
  network: ws
  port: 8880
  server: 104.239.72.188
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /TelegramğŸ‡¨ğŸ‡³ @WangCai2 /?ed=2560
- alterId: 0
  cipher: ''
  encryption: none
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨3
  network: ws
  port: 8880
  server: 91.193.58.245
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³
- alterId: 0
  cipher: ''
  encryption: none
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨5
  network: ws
  port: 8880
  server: 147.78.140.29
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /TelegramU0001F1E8U0001F1F3
- alterId: 0
  cipher: ''
  encryption: none
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨15
  network: ws
  port: 8880
  server: 104.234.239.251
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: 0132166f-e702-48ed-a9e7-b07af768faf8
  ws-opts:
    headers:
      Host: cf.d3z.net
    path: /TelegramğŸ‡¨ğŸ‡³
- alterId: 0
  cipher: ''
  encryption: none
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨4
  network: ws
  port: 8880
  server: 156.238.18.17
  skip-cert-verify: false
  tfo: false
  tls: false
  type: vless
  udp: true
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: yd.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨30
  network: ws
  port: 8443
  server: 104.26.7.89
  servername: brmahasang.ahaysiahzangi.dpdns.org
  skip-cert-verify: true
  sni: brmahasang.ahaysiahzangi.dpdns.org
  tfo: false
  tls: true
  type: vless
  uuid: f5cf098f-5143-440f-a490-7fc24ff27fb0
  ws-opts:
    headers:
      Host: brmahasang.ahaysiahzangi.dpdns.org
    path: /?ed=2560
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  encryption: none
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨9
  network: ws
  port: 443
  server: 104.18.205.33
  servername: rayan-fg-2.hasan-kachal.filegear-sg.me
  skip-cert-verify: true
  sni: rayan-fg-2.hasan-kachal.filegear-sg.me
  tfo: false
  tls: true
  type: vless
  udp: true
  uuid: a1650c69-531c-441f-bc6a-bd43565000a4
  ws-opts:
    headers:
      Host: rayan-fg-2.hasan-kachal.filegear-sg.me
    path: /
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  flow: ''
  name: ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨33
  network: ws
  port: 443
  server: 104.19.173.68
  servername: rayan-fg-7.mohammad-janam.filegear-sg.me
  skip-cert-verify: true
  sni: rayan-fg-7.mohammad-janam.filegear-sg.me
  tfo: false
  tls: true
  type: vless
  uuid: e97a0128-4785-4323-a2a5-dd01ce49d359
  ws-opts:
    headers:
      Host: rayan-fg-7.mohammad-janam.filegear-sg.me
    path: /?ed=2560
- name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 06 #2'
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 443
  server: 162.159.133.85
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 04 #2'
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2053
  server: 162.159.129.11
  skip-cert-verify: true
  sni: vle.amclubsvip.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubsvip.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 05 #2 #2'
  network: ws
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  port: 2087
  server: 104.25.254.4
  skip-cert-verify: true
  sni: vle.amclubssss.dpdns.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: vle.amclubssss.dpdns.org
    path: /?ed=2560&PROT_TYPE=trojan&NAT64=true
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4789 | 2.17MB
  password: TN2YqghxeFDKZfLU
  port: 9037
  server: 80.92.204.106
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4796 | 0.628MB
  password: ZET59LF6DvCC8KVt
  port: 9005
  server: 80.92.204.106
  type: ss
- cipher: rc4-md5
  name: ğŸ‡©ğŸ‡ªDE-193.108.119.230-0293 | 14.193MB
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 193.108.119.230
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4847 | 2.313MB
  password: Sn5B7jTqr76aCJT8
  port: 9097
  server: 80.92.204.106
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4788 | 2.164MB
  password: VP8ZPxQpJtZRCjfZ
  port: 9080
  server: 80.92.204.106
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4786 | 2.245MB
  password: EXN3S3eQpjE7EJu8
  port: 9027
  server: 80.92.204.106
  type: ss
- cipher: aes-256-cfb
  name: ğŸ‡©ğŸ‡ªDE-80.92.204.106-4848 | 2.087MB
  password: XPtzA9sCug3SPR4c
  port: 9025
  server: 80.92.204.106
  type: ss
- alterId: 0
  cipher: ''
  client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 'ğŸ‡©ğŸ‡ªğŸ‘–TGé¢‘é“@stymei1ä¸¨21 #2'
  network: tcp
  port: 443
  reality-opts:
    public-key: RW2LSBmmSe02gQ2e4OGfNmggZbuO4trpafPiNqVEajs
    short-id: e0b8e166
  server: 5.34.214.154
  servername: ign.com
  skip-cert-verify: true
  sni: ign.com
  tfo: false
  tls: true
  type: vless
  uuid: fa92e9cd-b5be-4e00-8fc4-4543012d1fd0
- alterId: 0
  cipher: auto
  country: ğŸZZ
  delay: 692
  h2-opts: {}
  http-opts: {}
  name: å¾·å›½ - å…°æ²³ç•”æ—å ¡ - OVH SAS - 8
  network: ws
  port: 2083
  server: 172.67.72.15
  servername: blaze-ger-248.blazecloudmain.site
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: c208e0ae-6f6d-4745-99da-44a44744c530
  ws-opts:
    headers:
      HOST: blaze-ger-248.blazecloudmain.site
    path: /linkwsrt?ed=2560
- name: ğŸ‡©ğŸ‡ª å¾·å›½ 41
  network: tcp
  port: 38918
  server: 46.29.34.205
  tls: false
  type: vless
  udp: true
  uuid: fb9183fc-f0bb-4d19-8c8b-704b017d04b8
- client-fingerprint: firefox
  flow: xtls-rprx-vision
  name: 'ğŸ‡©ğŸ‡ª å¾·å›½ 42 #2'
  network: tcp
  port: 56701
  reality-opts:
    public-key: sW8BfHeovVzmbFuAnr9nH8oJaKYze6shKoKMdek5ai8
    short-id: 792147b8
  server: 152.53.231.109
  servername: addons.mozilla.org
  tls: true
  type: vless
  udp: true
  uuid: b1676447-0825-4b60-be37-735c9586735e
proxy-groups:
- name: âœˆï¸ é€‰æ‹©ä»£ç†
  proxies:
  - âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  - âš–ï¸ è´Ÿè½½å‡è¡¡
  - ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  - DIRECT
  type: select
- expected-status: 200
  include-all: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš¡ï¸ è‡ªåŠ¨ä¼˜é€‰
  timeout: 3000
  tolerance: 10
  type: url-test
  url: https://www.apple.com/library/test/success.html
- expected-status: 200
  include-all: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: âš–ï¸ è´Ÿè½½å‡è¡¡
  strategy: consistent-hashing
  timeout: 3000
  type: load-balance
  url: https://www.apple.com/library/test/success.html
- expected-status: 200
  include-all: true
  interval: 60
  lazy: true
  max-failed-times: 2
  name: ğŸ‘† æ‰‹åŠ¨é€‰æ‹©
  timeout: 3000
  type: select
  url: https://www.apple.com/library/test/success.html
rule-providers:
  geoip_cn_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_cn_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_cn.txt
  geoip_lan_ip:
    behavior: ipcidr
    format: text
    interval: 86400
    path: ./ruleset/geoip_lan_ip.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/geoip-rules-generated/geoip_private.txt
  geosite_!cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_!cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/geolocation-!cn.txt
  geosite_@!cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@!cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_!cn.txt
  geosite_@ads:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@ads.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_ads.txt
  geosite_@cn_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_@cn_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/collect_tag_cn.txt
  geosite_apple:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_apple.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/apple.txt
  geosite_bing:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_bing.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/bing.txt
  geosite_cn:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_cn.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/cn.txt
  geosite_connectivity_check:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_connectivity_check.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/connectivity-check.txt
  geosite_google:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_google.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/google.txt
  geosite_private_domains:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_private_domains.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/private.txt
  geosite_telegram:
    behavior: classical
    format: yaml
    interval: 86400
    path: ./ruleset/geosite_telegram.rules
    type: http
    url: https://cdn.jsdelivr.net/gh/busymilk/v2fly-domain-list-community_rule_set@main/clash-rules-generated/telegram.txt
  other_direct_applications:
    behavior: classical
    interval: 86400
    path: ./ruleset/other_direct_applications.yaml
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
  other_ssk_global_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_global_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  other_ssk_lan_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
  other_ssk_lan_non_ip:
    behavior: classical
    format: text
    interval: 86400
    path: ./sukkaw_ruleset/ssk_lan_non_ip.txt
    type: http
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
rules:
- DOMAIN,time.apple.com,DIRECT
- DOMAIN,cdn.jsdelivr.net,DIRECT
- DOMAIN,a.ppconverter.eu.org,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN-SUFFIX,ghproxy.com,DIRECT
- DOMAIN-SUFFIX,gofile.io,DIRECT
- DOMAIN-SUFFIX,facefusion.io,âœˆï¸ é€‰æ‹©ä»£ç†
- DOMAIN-SUFFIX,anaconda.com,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_direct_applications,DIRECT
- RULE-SET,other_ssk_lan_non_ip,DIRECT
- RULE-SET,geosite_private_domains,DIRECT
- RULE-SET,geosite_connectivity_check,DIRECT
- RULE-SET,geosite_@ads,REJECT
- RULE-set,geosite_apple,DIRECT
- RULE-SET,geosite_bing,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_google,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_telegram,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@!cn_domains,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,other_ssk_global_non_ip,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_@cn_domains,DIRECT
- RULE-SET,geosite_!cn,âœˆï¸ é€‰æ‹©ä»£ç†
- RULE-SET,geosite_cn,DIRECT
- RULE-SET,geoip_lan_ip,DIRECT
- RULE-SET,other_ssk_lan_ip,DIRECT
- RULE-SET,geoip_cn_ip,DIRECT
- MATCH,âœˆï¸ é€‰æ‹©ä»£ç†
sniffer:
  enable: true
  skip-domain:
  - Mijia Cloud
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: false
  stack: gvisor
unified-delay: true
